on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 1200s
          script: |
            cd ${{ secrets.WORK_DIR }} 
            git fetch 
            git checkout ${{ secrets.MAIN_BRANCH }} 
            git pull 
            docker stop api_registro_personas_eco || true
            docker rm api_registro_personas_eco -f
            docker rmi unca_test/economica/api_registro_personas_eco:latest -f
            docker container prune -f || true
            docker image prune -a || true
            docker build --no-cache --pull -t unca_test/economica/api_registro_personas_eco:latest .
            docker run --restart=always -d -p 7012:4000 -e DATABASE_URL="${{ secrets.DATABASE_URL }}" --name api_registro_personas_eco unca_test/economica/api_registro_personas_eco:latest
            exit
